//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaConexion3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizacion_Detalle
    {
        public int ID_Cotización_Detalle { get; set; }
        public double Cantidad_producto { get; set; }
        public string Medidas_producto { get; set; }
        public string Color_producto { get; set; }
        public string Observaciones { get; set; }
        public Nullable<double> Precio_producto { get; set; }
        public Nullable<int> ID_Cotizacion { get; set; }
        public Nullable<int> ID_Producto { get; set; }
    
        public virtual Cotizacion Cotizacion { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
